<?php

namespace Drupal\conreg\Service;

use Drupal\Core\Database\Statement\FetchAs;
use Drupal\Core\Database\Connection;
use Drupal\Core\Menu\MenuLinkManagerInterface;
use Drupal\Core\Messenger\MessengerInterface;

/**
 * Functions to help load and save events.
 */
class EventStorage {

  /**
   * Event fields that appear in the admin menu's per-event links.
   *
   * Changing any of these requires the menu link tree to be rebuilt, since
   * the per-event links are generated by derivers only during a rebuild.
   */
  public const MENU_FIELDS = ['event_name'];

  /**
   * Constructs an EventStorage service.
   *
   * @param \Drupal\Core\Database\Connection $connection
   *   The database connection.
   * @param \Drupal\Core\Messenger\MessengerInterface $messenger
   *   The messenger service.
   * @param \Drupal\Core\Menu\MenuLinkManagerInterface $menuLinkManager
   *   The menu link manager.
   */
  public function __construct(
    protected Connection $connection,
    protected MessengerInterface $messenger,
    protected MenuLinkManagerInterface $menuLinkManager,
  ) {}

  /**
   * Save an event in the database.
   *
   * @param array $entry
   *   An array containing all the fields of the database record.
   *
   * @return int|null
   *   The inserted record ID, or NULL on failure.
   */
  public function insert(array $entry): ?int {
    try {
      $id = $this->connection
        ->insert('conreg_events')
        ->fields($entry)
        ->execute();
    }
    catch (\Exception $e) {
      $this->messenger->addError(t(
        'Insert failed. Message = %message',
        ['%message' => $e->getMessage()]
      ));
      return NULL;
    }

    if ($id === NULL) {
      return NULL;
    }
    // Rebuilt outside the try block so a menu failure isn't reported as a
    // failed insert.
    $this->menuLinkManager->rebuild();
    return (int) $id;
  }

  /**
   * Update an event in the database.
   *
   * @param array $entry
   *   An array containing all the fields of the item to be updated.
   *
   * @return int
   *   The number of updated rows.
   */
  public function update(array $entry): int {
    $existing = $this->load(['eid' => $entry['eid']]);

    try {
      $updated = (int) $this->connection
        ->update('conreg_events')
        ->fields($entry)
        ->condition('eid', $entry['eid'])
        ->execute();
    }
    catch (\Exception $e) {
      $this->messenger->addError(t(
        'Update failed. Message = %message',
        ['%message' => $e->getMessage()]
      ));
      return 0;
    }

    if ($existing && $this->menuFieldsChanged($existing, $entry)) {
      $this->menuLinkManager->rebuild();
    }
    return $updated;
  }

  /**
   * Delete an event from the database.
   *
   * @param array $entry
   *   An array containing at least the event identifier 'eid'.
   */
  public function delete(array $entry): void {
    $this->connection
      ->delete('conreg_events')
      ->condition('eid', $entry['eid'])
      ->execute();
    $this->menuLinkManager->rebuild();
  }

  /**
   * Checks whether an update changes any field shown in the admin menu.
   *
   * @param array $existing
   *   The event record before the update.
   * @param array $entry
   *   The fields being updated.
   *
   * @return bool
   *   TRUE if any of MENU_FIELDS is being set to a different value.
   */
  protected function menuFieldsChanged(array $existing, array $entry): bool {
    foreach (self::MENU_FIELDS as $field) {
      // Database values come back as strings, so compare as strings.
      if (array_key_exists($field, $entry) && (string) $entry[$field] !== (string) $existing[$field]) {
        return TRUE;
      }
    }
    return FALSE;
  }

  /**
   * Load a single event from the database.
   *
   * @param array $entry
   *   An associative array of field/value conditions.
   *
   * @return array|false
   *   The event record as an associative array, or FALSE if not found.
   */
  public function load(array $entry = []): array|false {
    $select = $this->connection
      ->select('conreg_events', 'e')
      ->fields('e');

    foreach ($entry as $field => $value) {
      $select->condition($field, $value);
    }

    return $select->execute()->fetchAssoc();
  }

  /**
   * Load multiple events from the database.
   *
   * @param array $entry
   *   An associative array of field/value conditions.
   *
   * @return array
   *   An array of event records.
   */
  public function loadAll(array $entry = []): array {
    $select = $this->connection
      ->select('conreg_events', 'e')
      ->fields('e');

    foreach ($entry as $field => $value) {
      $select->condition($field, $value);
    }

    return $select->execute()->fetchAll(FetchAs::Associative);
  }

  /**
   * Get a list of event options.
   *
   * @return array
   *   An associative array keyed by event ID, containing event names.
   */
  public function eventOptions(): array {
    return $this->connection
      ->select('conreg_events', 'e')
      ->fields('e', ['eid', 'event_name'])
      ->orderBy('event_name')
      ->execute()
      ->fetchAll(FetchAs::Associative);
  }

}
