<?php

/**
 * @file
 * Install, update and uninstall functions for the conreg_planz module.
 */

// cspell:ignore badgeid

/**
 * Implements hook_requirements().
 */
function conreg_planz_requirements($phase) {
  $requirements = [];
  return $requirements;
}

/**
 * Implements hook_install().
 *
 * Creates some default entries on this module custom table.
 *
 * @see hook_install()
 * @ingroup conreg_planz
 */
function conreg_planz_install() {
}

/**
 * Implements hook_schema().
 *
 * Defines the database tables used by this module.
 *
 * @see hook_schema()
 * @ingroup conreg_planz
 */
function conreg_planz_schema() {
  // Create table conreg_planz (mid int primary key, planz_user_id varchar(255) not null, update_date int not null);.
  $schema['conreg_planz'] = [
    'description' => 'Stores events on the registration system.',
    'fields' => [
      'mid' => [
        'type' => 'int',
        'not null' => TRUE,
        'description' => 'Primary Key: Unique event ID.',
      ],
      'badgeid' => [
        'type' => 'varchar',
        'length' => 15,
        'not null' => TRUE,
        'description' => 'Name of the event.',
      ],
      'update_date' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Unix timestamp for the date and time last updated.',
      ],
    ],
    'primary key' => ['mid'],
  ];

  return $schema;
}
