<?php

/**
 * @file
 * Install file for Conreg. Install database schema.
 */

use Drupal\Core\Database\Database;

/**
 * Implements hook_requirements().
 */
function conreg_requirements($phase) {
  $requirements = [];
  if ($phase == 'install') {
    if (!class_exists('\Stripe\Stripe')) {
      $requirements['addressing_library'] = [
        'description' => t('ConReg requires the stripe/stripe-php library. Please see README for install instructions.'),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
  }

  return $requirements;
}

/**
 * Implements hook_install().
 */
function conreg_install() {
  $database = \Drupal::database();

  // Only create a default event if none exist.
  $exists = $database->select('conreg_events', 'e')
    ->fields('e', ['eid'])
    ->range(0, 1)
    ->execute()
    ->fetchField();

  if (!$exists) {
    $database->insert('conreg_events')
      ->fields([
        'event_name' => 'Default event',
        'is_open' => 1,
      ])
      ->execute();
  }
}

/**
 * Implements hook_schema().
 *
 * Defines the database tables used by this module.
 *
 * @see hook_schema()
 * @ingroup conreg
 */
function conreg_schema() {

  // Create table conreg_events (eid int auto_increment primary key, event_name
  // varchar(255) not null, is_open tinyint not null default '1');.
  $schema['conreg_events'] = [
    'description' => 'Stores events on the registration system.',
    'fields' => [
      'eid' => [
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Primary Key: Unique event ID.',
      ],
      'event_name' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'description' => 'Name of the event.',
      ],
      'is_open' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 1,
        'size' => 'tiny',
        'description' => 'Set to 1 if event is open for registration.',
      ],
    ],
    'primary key' => ['eid'],
  ];

  $schema['conreg_members'] = [
    'description' => 'Stores member details for convention registrations.',
    'fields' => [
      'mid' => [
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Primary Key: Unique member ID.',
      ],
      // Alter table conreg_members add eid int NOT NULL default '1' after mid;.
      'eid' => [
        'type' => 'int',
        'not null' => TRUE,
        'description' => 'Foreign Key: Event ID.',
      ],
      'lead_mid' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => "Member ID of lead member (to link groups who register together)",
      ],
      'random_key' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => "A random generated key to provide some security in payment URL",
      ],
      'member_no' => [
        'type' => 'int',
        'not null' => FALSE,
        'default' => 0,
        'description' => "Member number - assigned once approved.",
      ],
      'language' => [
        'type' => 'varchar',
        'description' => "Member language",
        'length' => 8,
        'not null' => TRUE,
      ],
      // Alter table conreg_members modify column member_type varchar(16);.
      'member_type' => [
        'type' => 'varchar',
        'length' => 16,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Type of membership.',
      ],
      // Base type column removed. To remove from database use: update
      // conreg_members set member_type = base_type; alter table conreg_members
      // drop base_type;
      //
      // alter table conreg_members add days varchar(16) NULL after member_type;
      // update conreg_members set days='W' where days is NULL or days='';.
      'days' => [
        'type' => 'varchar',
        'length' => 16,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Selected day codes separated by |',
      ],
      // Days desc column removed. Remove from database with: alter table
      // conreg_members drop days_desc;
      //
      // alter table conreg_members add communication_method varchar(1) NULL
      // after member_type;.
      'communication_method' => [
        'type' => 'varchar',
        'length' => 1,
        'not null' => TRUE,
        'default' => '',
        'description' => 'E=Electronic, P=Paper, B=Both.',
      ],
      'is_approved' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'size' => 'tiny',
        'description' => 'Set to 1 if member wishes to volunteer to help.',
      ],
      'approver_uid' => [
        'type' => 'int',
        'not null' => FALSE,
        'default' => 0,
        'description' => "User ID of the admin who approved the member.",
      ],
      'first_name' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
        'description' => 'First name of the member.',
      ],
      'last_name' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Last name of the member.',
      ],
      'badge_name' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Badge name of the member.',
      ],
      // Alter table conreg_members add badge_type varchar(1) NULL after
      // badge_name; update conreg_members set badge_type='A';
      //
      // alter table conreg_members modify column badge_type varchar(4);.
      'badge_type' => [
        'type' => 'varchar',
        'length' => 4,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Type of Badge (e.g. Attending, Guest, Committee, Dealer).',
      ],
      'display' => [
        'type' => 'varchar',
        'length' => 1,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Display in membership list - F=Full Name, B=Badge Name, N=Not at all.',
      ],
      'email' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Email address of the member (only required for first member).',
      ],
      'street' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Street address of the member.',
      ],
      // Alter table conreg_members add street2 varchar(255) NULL after street;.
      'street2' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Street address line 2 of the member.',
      ],
      'city' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Town/city address of the member.',
      ],
      'county' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'State/county of the member.',
      ],
      'postcode' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Postcode of the member.',
      ],
      'country' => [
        'type' => 'varchar',
        'length' => 2,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Country of the member.',
      ],
      'phone' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Phone number of the member.',
      ],
      'birth_date' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => FALSE,
        'description' => "Unix timestamp for the member's date of birth.",
      ],
      // Alter table conreg_members add age int NULL default "0" after
      // birth_date;.
      'age' => [
        'type' => 'int',
        'not null' => FALSE,
        'default' => 0,
        'description' => 'Age of member.',
      ],
      'is_volunteer' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'size' => 'tiny',
        'description' => 'Set to 1 if member wishes to volunteer to help.',
      ],
      'member_price' => [
        'type' => 'numeric',
        'precision' => 10,
        'scale' => 2,
        'not null' => TRUE,
        'default' => 0.0,
        'description' => 'Price for this member (excluding add-on).',
      ],
      // Alter table conreg_members add member_total numeric(10,2) NOT NULL
      // default "0" after member_price;.
      'member_total' => [
        'type' => 'numeric',
        'precision' => 10,
        'scale' => 2,
        'not null' => TRUE,
        'default' => 0.0,
        'description' => 'Total price for member (including add-on).',
      ],
      'is_paid' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'size' => 'tiny',
        'description' => 'Set to 1 if payment complete.',
      ],
      'payment_method' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
        'description' => 'How payment received (Stripe, PayPal, etc).',
      ],
      'payment_amount' => [
        'type' => 'numeric',
        'precision' => 10,
        'scale' => 2,
        'not null' => TRUE,
        'default' => 0.0,
        'description' => 'Total amount received for all members in group.',
      ],
      'payment_id' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Payment confirmation code from Stripe or other payment system.',
      ],
      // Alter table conreg_members add comment varchar(1024) NULL after
      // payment_id;.
      'comment' => [
        'type' => 'varchar',
        'length' => 1024,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Admin comments about member.',
      ],
      'add_on' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Optional addons to membership.',
      ],
      // Alter table conreg_members add add_on_price numeric(10,2) default "0"
      // after add_on;
      //
      // alter table conreg_members modify add_on_price numeric(10,2);.
      'add_on_price' => [
        'type' => 'numeric',
        'precision' => 10,
        'scale' => 2,
        'not null' => FALSE,
        'default' => 0.0,
        'description' => 'Price of add-on for this member.',
      ],
      'add_on_info' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Extra information about add-on.',
      ],
      'join_date' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Unix timestamp for the date and time registered.',
      ],
      // Alter table conreg_members add update_date int NOT NULL default "0"
      // after join_date;.
      'update_date' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Unix timestamp for the date and time last updated.',
      ],
      'login_exp_date' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Unix timestamp for the date and time member was checked in.',
      ],
      // Alter table conreg_members add is_checked_in int NOT NULL default "0"
      // after update_date;.
      'is_checked_in' => [
        'type' => 'int',
        'not null' => FALSE,
        'default' => 0,
        'size' => 'tiny',
        'description' => 'True if member has checked in at convention.',
      ],
      // Alter table conreg_members add check_in_date int NOT NULL default "0"
      // after is_checked_in;.
      'check_in_date' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Unix timestamp for the date and time member was checked in.',
      ],
      // Alter table conreg_members add check_in_by int NULL after
      // check_in_date;.
      'check_in_by' => [
        'type' => 'int',
        'not null' => FALSE,
        'description' => 'The Drupal user ID who checked the member in.',
      ],
      // Alter table conreg_members add is_deleted int NOT NULL default "0"
      // after join_date;.
      'is_deleted' => [
        'type' => 'int',
        'not null' => FALSE,
        'default' => 0,
        'size' => 'tiny',
        'description' => 'True if member is deleted.',
      ],
    ],
    'primary key' => ['mid'],
    'indexes' => [
      'name' => ['last_name', 'first_name'],
      'lead_mid' => ['lead_mid'],
    ],
  ];

  // Create table conreg_upgrades (upgid int auto_increment primary key, eid int
  // not null, mid int not null, lead_mid int not null, from_type varchar(16),
  // from_days varchar(16), to_type varchar(16), to_days varchar(16),
  // to_badge_type varchar(16), upgrade_price numeric(10,2), is_paid tinyint,
  // payment_method varchar(255), payment_amount numeric(10,2), payment_id
  // varchar(255), upgrade_date int not null);.
  $schema['conreg_upgrades'] = [
    'description' => 'Stores member upgrades.',
    'fields' => [
      'upgid' => [
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Primary Key: Unique group ID.',
      ],
      'eid' => [
        'type' => 'int',
        'not null' => TRUE,
        'description' => 'Foreign Key: Event ID.',
      ],
      'mid' => [
        'type' => 'int',
        'not null' => TRUE,
        'description' => 'Foreign Key: Member ID.',
      ],
      'lead_mid' => [
        'type' => 'int',
        'not null' => TRUE,
        'description' => 'Foreign Key: Member ID.',
      ],
      'from_type' => [
        'type' => 'varchar',
        'length' => 16,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Member type upgrading from.',
      ],
      'from_days' => [
        'type' => 'varchar',
        'length' => 16,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Member days upgrading from',
      ],
      'to_type' => [
        'type' => 'varchar',
        'length' => 16,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Member type upgraded to.',
      ],
      'to_days' => [
        'type' => 'varchar',
        'length' => 16,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Member days upgraded to',
      ],
      'to_badge_type' => [
        'type' => 'varchar',
        'length' => 16,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Badge type upgraded to.',
      ],
      'upgrade_price' => [
        'type' => 'numeric',
        'precision' => 10,
        'scale' => 2,
        'not null' => TRUE,
        'default' => 0.0,
        'description' => 'Price for this member (excluding add-on).',
      ],
      'is_paid' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'size' => 'tiny',
        'description' => 'Set to 1 if payment complete.',
      ],
      'payment_method' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
        'description' => 'How payment received (Stripe, PayPal, etc).',
      ],
      'payment_amount' => [
        'type' => 'numeric',
        'precision' => 10,
        'scale' => 2,
        'not null' => TRUE,
        'default' => 0.0,
        'description' => 'Total amount received for all members in group.',
      ],
      'payment_id' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Payment confirmation code from Stripe or other payment system.',
      ],
      // Alter table conreg_upgrades add upgrade_date int NOT NULL default "0"
      // after payment_id;.
      'upgrade_date' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Unix timestamp for the date and time member was upgraded.',
      ],
    ],
    'primary key' => ['upgid'],
  ];

  // Create table conreg_payments (payid int auto_increment primary key,
  // random_key int not null, created_date int not null, session_id
  // varchar(255), paid_date int, payment_method varchar(255), payment_amount
  // numeric(10,2), payment_ref varchar(255));.
  $schema['conreg_payments'] = [
    'description' => 'Stores member upgrades.',
    'fields' => [
      'payid' => [
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Primary Key: Unique group ID.',
      ],
      'random_key' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => "A random generated key to provide some security in payment URL",
      ],
      'created_date' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Unix timestamp for the date and time member was upgraded.',
      ],
      'paid_date' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Unix timestamp for the date and time member was upgraded.',
      ],
      'payment_method' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
        'description' => 'How payment received (Stripe, PayPal, etc).',
      ],
      'payment_amount' => [
        'type' => 'numeric',
        'precision' => 10,
        'scale' => 2,
        'not null' => TRUE,
        'default' => 0.0,
        'description' => 'Total amount received for all members in group.',
      ],
      'payment_ref' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Payment confirmation code from Stripe or other payment system.',
      ],
    ],
    'primary key' => ['payid'],
  ];

  // Payment Sessions table, used to store Stripe session keys.
  $schema['conreg_payment_sessions'] = [
    'description' => 'Stores member upgrades.',
    'fields' => [
      'paysessionid' => [
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Primary Key: Unique payment session ID.',
      ],
      'payid' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => "Payment ID that the session belongs to.",
      ],
      'session_id' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Stripe Session ID.',
      ],
    ],
    'primary key' => ['paysessionid'],
    'indexes' => [
      'idx_conreg_payment_sessions_payid' => ['payid'],
      'idx_conreg_payment_sessions_session_id' => ['session_id'],
    ],
  ];

  // Create table conreg_payment_lines (lineid int auto_increment primary key,
  // payid int not null, mid int not null, payment_type varchar(255) not null,
  // line_desc varchar(255) not null, amount numeric(10,2) not null);.
  $schema['conreg_payment_lines'] = [
    'description' => 'Stores member upgrades.',
    'fields' => [
      'lineid' => [
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Primary Key: Unique group ID.',
      ],
      'payid' => [
        'type' => 'int',
        'not null' => TRUE,
        'description' => 'Foreign Key: Payment ID.',
      ],
      'mid' => [
        'type' => 'int',
        'not null' => FALSE,
        'description' => 'Foreign Key: Member ID.',
      ],
      'payment_type' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Identifies the type of payment, such as "member", "upgrade".',
      ],
      'line_desc' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Line description to be displayed for the field group (if null or blank, no title displayed).',
      ],
      'amount' => [
        'type' => 'numeric',
        'precision' => 10,
        'scale' => 2,
        'not null' => TRUE,
        'default' => 0.0,
        'description' => 'Amount of payment line.',
      ],
    ],
    'primary key' => ['lineid'],
  ];

  // Create table conreg_member_options (mid int not null, optid int not null,
  // is_selected tinyint not null default '1', option_detail varchar(255),
  // update_date int NOT NULL, primary key (mid, optid));.
  $schema['conreg_member_options'] = [
    'description' => 'Stores member option choices.',
    'fields' => [
      'mid' => [
        'type' => 'int',
        'not null' => TRUE,
        'description' => 'Compound Primary Key: Member ID.',
      ],
      'optid' => [
        'type' => 'int',
        'not null' => TRUE,
        'description' => 'Compound Primary Key: Option ID.',
      ],
      'is_selected' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 1,
        'size' => 'tiny',
        'description' => 'Set to 1 if option has been selected.',
      ],
      'option_detail' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Optional text details entered for the option.',
      ],
      // Alter table conreg_member_options add update_date int NOT NULL default
      // "0" after option_detail;.
      'update_date' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Unix timestamp for the date and time last updated.',
      ],
    ],
    'primary key' => ['mid', 'optid'],
  ];

  // Create table conreg_member_addons (addonid int auto_increment primary key,
  // mid int not null, addon_name varchar(255) not null, addon_option
  // varchar(255), addon_info varchar(255), addon_amount numeric(10,2), payid
  // int, is_paid tinyint, payment_ref varchar(255));.
  $schema['conreg_member_addons'] = [
    'description' => 'Stores member add-ons.',
    'fields' => [
      'addonid' => [
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Primary Key: Unique option ID.',
      ],
      'mid' => [
        'type' => 'int',
        'not null' => TRUE,
        'description' => 'Compound Primary Key: Member ID.',
      ],
      'addon_name' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Name of the add-on.',
      ],
      'addon_option' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Name of the selected option.',
      ],
      'addon_info' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Extra information about add-on.',
      ],
      'addon_amount' => [
        'type' => 'numeric',
        'precision' => 10,
        'scale' => 2,
        'not null' => TRUE,
        'default' => 0.0,
        'description' => 'Total amount received for all members in group.',
      ],
      // Alter table conreg_member_addons add payid int after addon_amount;.
      'payid' => [
        'type' => 'int',
        'not null' => FALSE,
        'description' => 'Compound Primary Key: Member ID.',
      ],
      'is_paid' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'size' => 'tiny',
        'description' => 'Set to 1 if payment complete.',
      ],
      'payment_ref' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Payment confirmation code from Stripe or other payment system.',
      ],
    ],
    'primary key' => ['addonid'],
  ];

  // Create table conreg_member_clickup_options (mid int not null, option_group
  // varchar(32) NOT NULL, clickup_task_id varchar(255) NOT NULL, update_date
  // int NOT NULL, primary key (mid, option_group));.
  $schema['conreg_member_clickup_options'] = [
    'description' => 'Stores member click-up task IDs.',
    'fields' => [
      'mid' => [
        'type' => 'int',
        'not null' => TRUE,
        'description' => 'Compound Primary Key: Member ID.',
      ],
      'option_group' => [
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Group of options sharing a single task.',
      ],
      'clickup_task_id' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Task ID returned from ClickUp.',
      ],
      'update_date' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Unix timestamp for the date and time last updated.',
      ],
    ],
    'primary key' => ['mid', 'option_group'],
  ];

  return $schema;
}

/**
 * Remove any "reference.countries" from settings.
 */
function conreg_update_9001() {
  foreach (\Drupal::configFactory()->listAll('conreg.settings') as $key) {
    $config = \Drupal::configFactory()->getEditable($key);
    $config->clear("reference.countries");
    $config->save();
  }
}

/**
 * Add language field to conreg_members.
 */
function conreg_update_9002() {
  $spec = [
    'type' => 'varchar',
    'description' => "Member language",
    'length' => 2,
    'not null' => TRUE,
    'initial' => 'en',
  ];
  $schema = Database::getConnection()->schema();
  $schema->addField('conreg_members', 'language', $spec);
}

/**
 * Add payment sessions table.
 *
 * Move Stripe session ID from payments table to payment sessions. Drop session
 * ID from payments table.
 */
function conreg_update_9003() {
  $conreg_payment_sessions = [
    'description' => 'Stores member upgrades.',
    'fields' => [
      'paysessionid' => [
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Primary Key: Unique payment session ID.',
      ],
      'payid' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => "Payment ID that the session belongs to.",
      ],
      'session_id' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Stripe Session ID.',
      ],
    ],
    'primary key' => ['paysessionid'],
  ];
  $db = Database::getConnection();
  $schema = $db->schema();
  $schema->createTable('conreg_payment_sessions', $conreg_payment_sessions);
  $db->query('INSERT INTO {conreg_payment_sessions} (payid, session_id) SELECT payid, session_id FROM {conreg_payments}');
  $schema->dropField('conreg_payments', 'session_id');
}

/**
 * Add indexes to payment sessions table.
 */
function conreg_update_9004() {
  $conreg_payment_sessions = [
    'description' => 'Stores member upgrades.',
    'fields' => [
      'paysessionid' => [
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Primary Key: Unique payment session ID.',
      ],
      'payid' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => "Payment ID that the session belongs to.",
      ],
      'session_id' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'default' => '',
        'description' => 'Stripe Session ID.',
      ],
    ],
    'primary key' => ['paysessionid'],
    'indexes' => [
      'idx_conreg_payment_sessions_payid' => ['payid'],
      'idx_conreg_payment_sessions_session_id' => ['session_id'],
    ],
  ];

  $db = Database::getConnection();
  $schema = $db->schema();
  $schema->addIndex('conreg_payment_sessions', 'idx_conreg_payment_sessions_payid', ['payid'], $conreg_payment_sessions);
  $schema->addIndex('conreg_payment_sessions', 'idx_conreg_payment_sessions_session_id', ['session_id'], $conreg_payment_sessions);
}
