<?php

/**
 * @file
 * Install, update and uninstall functions for the conreg_airtable module.
 */

/**
 * Implements hook_requirements().
 */
function conreg_airtable_requirements($phase) {
  $requirements = [];
  if ($phase == 'install') {
    if (!class_exists('\Stripe\Stripe')) {
      $requirements['addressing_library'] = [
        'description' => t('Simple Convention Registration requires the stripe/stripe-php library. Please see README for install instructions.'),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
  }

  return $requirements;
}

/**
 * Implements hook_install().
 *
 * Creates some default entries on this module custom table.
 *
 * @see hook_install()
 * @ingroup conreg_airtable
 */
function conreg_airtable_install() {
}

/**
 * Implements hook_schema().
 *
 * Defines the database tables used by this module.
 *
 * @see hook_schema()
 * @ingroup conreg_airtable
 */
function conreg_airtable_schema() {

  // Create table conreg_events (eid int auto_increment primary key, event_name varchar(255) not null, is_open tinyint not null default '1');.
  $schema['conreg_airtable_members'] = [
    'description' => 'Stores events on the registration system.',
    'fields' => [
      'mid' => [
        'type' => 'int',
        'not null' => TRUE,
        'description' => 'Primary Key: Unique event ID.',
      ],
      'airtable_id' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'description' => 'Name of the event.',
      ],
    ],
    'primary key' => ['mid'],
  ];

  return $schema;
}
