<?php

/**
 * @file
 * Module file for conreg_airtable.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\conreg_airtable\Hook\ConregAirtableHooks;
use Drupal\conreg\Member;

/**
 * Implements hook_convention_member_added().
 */
#[LegacyHook]
function conreg_airtable_convention_member_added(Member $member) {
  \Drupal::service(ConregAirtableHooks::class)->conventionMemberAdded($member);
}

/**
 * Implements hook_convention_member_updated().
 */
#[LegacyHook]
function conreg_airtable_convention_member_updated(Member $member) {
  \Drupal::service(ConregAirtableHooks::class)->conventionMemberUpdated($member);
}

/**
 * Implements hook_convention_member_deleted().
 */
#[LegacyHook]
function conreg_airtable_convention_member_deleted(Member $member) {
  \Drupal::service(ConregAirtableHooks::class)->conventionMemberDeleted($member);
}
