<?php

/**
 * @file
 * Module file for conreg_clickup.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\conreg_clickup\Hook\ConregClickupHooks;
use Drupal\conreg\Member;

/**
 * Implements hook_convention_member_updated().
 */
#[LegacyHook]
function conreg_clickup_convention_member_updated(Member $member) {
  \Drupal::service(ConregClickupHooks::class)->conventionMemberUpdated($member);
}
